version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./migrations:/migrations
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  admin-bot:
    build: ./admin-bot
    depends_on:
      - postgres
      - redis

  worker-bot:
    build: ./worker-bot
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"